server: # REST server
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    password: "youshallnotpass"
    ws:
      port: 7070
      host: 0.0.0.0
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
    sentryDsn: ""
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 600
    gc-warnings: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics